apps/clientes/urls.py
from django.conf.urls import include, url
from .views import ClienteList, ClienteDetail, ClienteUpdate, SaveImage, practica, ClienteDel

urlpatterns = [
    url(r'^registrar_cliente/$', 'apps.clientes.views.RegistrarCliente', name='registrar_cliente'),
    url(r'^listar_cliente/$', ClienteList.as_view(), name='listar_cliente'),
    url(r'^detail_cliente/(?P<pk>\d+)$', ClienteDetail.as_view(), name='cliente_detail'),
    url(r'^update_cliente/(?P<pk>\d+)$', ClienteUpdate.as_view(), name='cliente_update'),
    url(r'^delete_cliente/(?P<id>\d+)$', 'apps.clientes.views.eliminarCliente', name='cliente_delete'),
    url(r'^registrar_emp/$', 'apps.clientes.views.addEmpresa', name='registrar_empresa'),
    url(r'^registrar_trami/$', 'apps.clientes.views.addTramite', name='registrar_trami'),

    url(r'^registrar_clinic/$', 'apps.clientes.views.addClinica', name='registrar_clinic'),
    url(r'^detalle_cliente/(?P<pk>\d+)$', 'apps.clientes.views.detalleCliente', name='detallecliente'),
    url(r'^save_image/(?P<codigo>[\w\-]+)/$', SaveImage.as_view(), name='salvar_imagen'),
    url(r'^client/', 'apps.clientes.views.client', name="client"),
    url(r'^del/$', ClienteDel.as_view()),
    url(r'^practica/$', practica.as_view(), name='pracica'),
    url(r'^servicios_cliente/(?P<pk>\d+)$', 'apps.clientes.views.serviciosCliente', name="servicios_cliente"),
    url(r'^costos_por_cliente/(?P<pk>\d+)$', 'apps.clientes.views.definir_costos_cliente', name='costos_por_cliente'),
    url(r'^cobro_cliente/(?P<pk>\d+)$', 'apps.clientes.views.cobroCliente', name='cobro_cliente'),
    url(r'^detallecobro/(?P<pk>\d+)$', 'apps.clientes.views.detalleCobro', name='detallecobro'),
    url(r'^reportecobro/(?P<pk>\d+)$', 'apps.clientes.views.reporteCobro', name='reportecobro'),
    # url(r'^save_image/(?P<codigo>[\w\-]+)$', 'apps.clientes.views.SaveImage', name='salvar_imagen'),
]

apps/empresas/urls.py
from django.conf.urls import include, url
from .views import RegistarEmpresa, EmpresaList, EmpresaDetail, EmpresaUpdateView, EmpresaDelete

urlpatterns = [
    url(r'^registrar_empresa/$', RegistarEmpresa.as_view(), name='registrar_empresa'),
    url(r'^listar_empresa/$', EmpresaList.as_view(), name='listar_empresa'),
    url(r'^detail_empresa/(?P<pk>\d+)$', EmpresaDetail.as_view(), name='empresa_detail'),
    url(r'^update_empresa/(?P<pk>\d+)$', EmpresaUpdateView.as_view(), name='empresa_update'),
    #url(r'^delete_empresa/(?P<pk>\d+)$', EmpresaDelete.as_view(), name='empresa_delete'),
    url(r'^delete_empresa/(?P<id>\d+)$', 'apps.empresas.views.eliminar', name='empresa_delete'),
]

goodlife_2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # INICIO
    url(r'^', include('apps.inicio.urls'), name='inicio'),

    # EMPRESAS
    url(r'^', include('apps.empresas.urls'), name='empresas'),

    # CLINICAS
    url(r'^', include('apps.clinicas.urls'), name='clinicas'),

    # CLIENTES
    url(r'^', include('apps.clientes.urls'), name='clientes'),

    # TRAMITES
    url(r'^', include('apps.tramites.urls'), name='tramites'),

    # CONFIGURACION
    url(r'^', include('apps.config.urls'), name='config'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/clientes/models.py
from django.db import models
from apps.empresas.models import Empresa
from apps.tramites.models import Tramite, TramiteAfp
from apps.clinicas.models import Clinica

DEP_CHOICES = (
('Beni', 'Beni'),
('Chuquisaca', 'Chuquisaca'),
('Cochabamba', 'Cochabamba'),
('La Paz', 'La Paz'),
('Oruro', 'Oruro'),
('Pando', 'Pando'),
('Potosi', 'Potosi'),
('Santa Cruz', 'Santa Cruz'),
('Tarija', 'Tarija'),
)

class Cliente(models.Model):
	codigo_gl = models.CharField(max_length=20)
	fecha_ingreso = models.DateField(null=True, blank=True)
	ciudad_origen = models.CharField(max_length=50, choices=DEP_CHOICES)
	nombres = models.CharField(max_length=100)
	apellidos = models.CharField(max_length=100)
	fecha_naciemiento = models.DateField(null=True, blank=True)
	edad = models.IntegerField()
	ci = models.BigIntegerField()
	expedido = models.CharField(max_length=100, null=True, blank=True)
	telefono = models.IntegerField(null=True, blank=True)
	cel = models.IntegerField(null=True, blank=True)
	foto = models.ImageField(upload_to='clientes', null=True, blank=True)
	activo = models.BooleanField(default=True)
	empresa = models.ForeignKey(Empresa, null=True, blank=True)
	tramite = models.ForeignKey(Tramite, null=True, blank=True)
	afps = models.ForeignKey(TramiteAfp, null=True, blank=True)
	clinica = models.ForeignKey(Clinica, null=True, blank=True)
	persona_referencia = models.CharField(max_length=150, null=True, blank=True)
	telefono_per_referencia = models.IntegerField(null=True, blank=True)
	cel_per_referencia = models.IntegerField(null=True, blank=True)
	usuario = models.CharField(max_length=50, null=True, blank=True)
	fecha_inactivo = models.DateField(null=True, blank=True)
	seguro = models.CharField(max_length=50, null=True, blank=True)

	def __unicode__(self):
		return "%s-%s-%s" % (self.codigo_gl, self.nombres, self.apellidos)


class DtoCodigo(models.Model):
	departamento = models.CharField(max_length=50, choices=DEP_CHOICES)
	short = models.CharField(max_length=4, null=True, blank=True)
	cantidad = models.IntegerField(default=0)

	def __unicode__(self):
		return "%s - %s" % (self.departamento, self.cantidad)


class ServiciosCostos(models.Model):    # Cobros Default
	servicio = models.CharField(max_length=100, null=True, blank=True)
	costo = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

	def __unicode__(self):
		return "%s - %s" % (self.servicio, self.costo)


class CostosPorCliente(models.Model):
	cliente = models.ForeignKey(Cliente, null=True, blank=True)
	servicio = models.CharField(max_length=100)
	costo = models.DecimalField(max_digits=10, decimal_places=2)
	pago = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
	cancelado = models.BooleanField(default=False)

	def __unicode__(self):
		return "%s - %s -%s" % (self.cliente.codigo_gl, self. servicio, self.costo)


class ServiciosCobroCliente(models.Model): # Cabecera de Cobros
	cliente = models.ForeignKey(Cliente, null=True, blank=True)
	fecha = models.DateField()
	num_recibo = models.IntegerField()
	total = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

	def __unicode__(self):
		return "%s - %s" % (self.cliente.codigo_gl, self.fecha)


class ServiciosCobroClienteDetalle(models.Model): # Detalle de Cobros
	cobro = models.ForeignKey(ServiciosCobroCliente, null=True, blank=True)
	servicio = models.CharField(max_length=100)
	costo = models.DecimalField(max_digits=10, decimal_places=2)
	pago = models.DecimalField(max_digits=10, decimal_places=2)
	amortizacion = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

	def __unicode__(self):
		return "%s - %s - %s - %s" % (self.cobro, self.servicio, self.costo, self.pago)


class CarteraCliente(models.Model): # Cabecera de Cobros
	cliente = models.ForeignKey(Cliente, null=True, blank=True)
	examen = models.CharField(max_length=100)
	deuda = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
	pago = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
	fecha = models.DateField()
	num_recibo = models.IntegerField(null=True, blank=True)
	
	def __unicode__(self):
		return "%s - %s" % (self.cliente.codigo_gl, self.fecha)


class CarteraCabezera(models.Model): # Cabecera de Cobros
	cliente = models.ForeignKey(Cliente, null=True, blank=True)
	fecha = models.DateField()
	num_recibo = models.IntegerField(null=True, blank=True)
	total = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
	saldo = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
	
	def __unicode__(self):
		return "%s - %s" % (self.cliente.codigo_gl, self.fecha)


class CarteraDetalle(models.Model):
	cartera_c = models.ForeignKey(CarteraCabezera, null=True, blank=True)
	examen = models.CharField(max_length=100)
	deuda = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
	pago = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)


class Documento(models.Model):
	poder = models.BooleanField()
	decl_enf_den_accid = models.BooleanField()
	avc_carnet_aseg = models.BooleanField()
	croquis_domicilio = models.BooleanField()
	cert_nacimiento_aseg = models.BooleanField()
	cert_trabajo = models.BooleanField()
	ci_asegurado = models.BooleanField()
	boleta_trabajo = models.BooleanField()
	cert_matrimonio = models.BooleanField()
	extracto_afp = models.BooleanField()
	cert_d_nacimiento_cony = models.BooleanField()
	actalizacion = models.BooleanField()
	ci_conyugue = models.BooleanField()
	contrato = models.BooleanField()
	cert_nac_hijos = models.BooleanField()
	costo_bs_item_contrato = models.BooleanField()
	ci_hijos = models.BooleanField()
	resolucion_invalidz_hijos = models.BooleanField()
	cliente = models.ForeignKey(Cliente, null=True, blank=True)

apps/empresas/models.py
from django.db import models


class Empresa(models.Model):
	razon_social = models.CharField(max_length=150)
	direccion = models.CharField(max_length=150)
	telefono1 = models.CharField(max_length=20, blank=True)
	telefono2 = models.CharField(max_length=20, blank=True)
	nro_patronal = models.CharField(max_length=50, blank=True)
	departamento = models.CharField(max_length=100)
	municipios = models.CharField(max_length=100)

	def __unicode__(self):
		return self.razon_social

apps/clientes/forms.py
from django import forms, http
from .models import Cliente, ServiciosCostos, CostosPorCliente


from django.forms import ModelForm
from django.forms import modelformset_factory

from apps.empresas.models import Empresa
from apps.tramites.models import Tramite, TramiteAfp
from apps.clinicas.models import Clinica


# class ClienteForm(forms.Form):
# 	codigo_gl = forms.CharField(max_length=20)
# 	fecha_ingreso = forms.DateField()
# 	ciudad_origen = forms.CharField()
# 	nombres = forms.CharField(max_length=100)
# 	apellidos = forms.CharField(max_length=100)
# 	edad = forms.IntegerField()
# 	ci = forms.IntegerField()
# 	telefono = forms.IntegerField()
# 	cel = forms.IntegerField()
# 	foto = forms.ImageField()
# 	activo = forms.CharField(max_length=20)
# 	empresa = forms.ModelChoiceField(queryset=Empresa.objects.all())
# 	tramite = forms.ModelChoiceField(queryset=Tramite.objects.all())
# 	afps = forms.ModelChoiceField(queryset=TramiteAfp.objects.all())
# 	clinica = forms.ModelChoiceField(queryset=Clinica.objects.all())
# 	persona_referencia = forms.CharField(max_length=150)
# 	telefono_per_referencia = forms.IntegerField()
# 	cel_per_referencia = forms.IntegerField()
# 	usuario = forms.CharField(max_length=50)

# 	class Meta:
# 		model = Cliente
DEP_CHOICES = (
('Beni', 'Beni'),
('Chuquisaca', 'Chuquisaca'),
('Cochabamba', 'Cochabamba'),
('La Paz', 'La Paz'),
('Oruro', 'Oruro'),
('Pando', 'Pando'),
('Potosi', 'Potosi'),
('Santa Cruz', 'Santa Cruz'),
('Tarija', 'Tarija'),
)

class ClienteForm(forms.Form):
	codigo_gl = forms.CharField(label="CODIG")
	ciudad_origen = forms.ChoiceField(label="CIUDAD ORIGEN", choices = DEP_CHOICES)
	nombres = forms.CharField(label="NOMBRES")
	apellidos = forms.CharField(label="APELLIDOS")
	fecha_naciemiento = forms.DateField(label="FECHA DE NACIMIENTO", required=False)
	edad = forms.IntegerField(label="EDAD")
	ci = forms.IntegerField(label="CI")
	expedido = forms.CharField(label="EXPEDIDO")
	telefono = forms.IntegerField(label="TELEFONO", required=False)
	cel = forms.IntegerField(label="CELULAR", required=False)
	foto = forms.ImageField(label="FOTO", required=False)
	activo = forms.BooleanField(label="ACITVO", initial=True, required=False)
	empresa = forms.ModelChoiceField(label="ENPRESA", queryset=Empresa.objects.all())
	tramite = forms.ModelChoiceField(label="TAMITE", queryset=Tramite.objects.all())
	afps = forms.ModelChoiceField(label="AFPS", queryset=TramiteAfp.objects.all())
	clinica = forms.ModelChoiceField(label="CLINICA", queryset=Clinica.objects.all())
	persona_referencia = forms.CharField(label="PERSONA REFERENCIA", required=False)
	telefono_per_referencia = forms.IntegerField(label="TELEFONO PER REFERENCIA", required=False)
	cel_per_referencia = forms.IntegerField(label="CELE_PER_REFERENCIA", required=False)
	fecha_inactivo = forms.DateField(label="FECHA_INACTIVO", required=False)
	seguro = forms.CharField(label="SEGURO", required=False)
	imagenf = forms.CharField(label="IMAGENF", required=False)
	
	# class Meta:
	# 	model = Cliente


CostosFormSet = modelformset_factory(ServiciosCostos, extra=0, fields=('servicio', 'costo'))


class CostosForm(CostosFormSet):

    def add_fields(self, form, index):

        super(CostosForm, self).add_fields(form, index)
        form.fields['servicio'].widget = forms.HiddenInput()


CostosPorClienteFormSet = modelformset_factory(CostosPorCliente, extra=0, fields=('servicio', 'costo', 'pago'))


class CostosPorClienteForm(CostosPorClienteFormSet):

    def add_fields(self, form, index):

        super(CostosPorClienteForm, self).add_fields(form, index)
        form.fields['servicio'].widget = forms.HiddenInput()


CobrosClienteFormSet = modelformset_factory(CostosPorCliente, extra=0, fields=('servicio', 'costo', 'pago'))


class CobrosClienteForm(CobrosClienteFormSet):

    def add_fields(self, form, index):
        super(CobrosClienteForm, self).add_fields(form, index)
        form.fields['servicio'].widget = forms.HiddenInput()
        form.fields['costo'].widget = forms.HiddenInput()
        form.fields['pago'].widget = forms.HiddenInput()
        form.fields['monto'] = forms.IntegerField(required=False)

apps/empresas/views.py
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect 

from .models import Empresa



class RegistarEmpresa(CreateView):
	template_name = 'empresas/registrar_empresa.html'
	model = Empresa
	fields = ('razon_social', 'direccion', 'telefono1', 'telefono2', 'nro_patronal', 'departamento', 'municipios')
	success_url = reverse_lazy('listar_empresa')


class EmpresaList(ListView):
	template_name = 'empresas/lista_empresa.html'
	model = Empresa


class EmpresaDetail(DetailView):
	template_name = 'empresas/detail_empresa.html'
	model = Empresa
	success_url = reverse_lazy('listar_empresa')


class EmpresaUpdateView(UpdateView):
	template_name = 'empresas/update_empresa.html'
	model = Empresa
	fields = ('razon_social', 'direccion', 'telefono1', 'telefono2', 'nro_patronal', 'departamento', 'municipios')
	success_url = reverse_lazy('listar_empresa')


class EmpresaDelete(DeleteView):
    model = Empresa
    success_url = reverse_lazy('listar_empresa')


def eliminar(request, id):
	p = Empresa.objects.get(id=id)
	p.delete()
	return HttpResponseRedirect(reverse_lazy('listar_empresa'))

templates/clientes/empresa.html
  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Modal title</h4>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>

templates/clientes/registrar_clienteOLD.html
{% extends 'base.html' %}

{% block content %}

  <div class="container">
    <h1 class="">Registrar Cliente Good Life</h1>
    <form class="form-horizontal" method='POST'>{% csrf_token %}
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="" class="col-sm-5 control-label2">Ciudad de origen:</label>
            <div class="col-sm-10">
              <!--input type="email" class="form-control" id="" name='ciudad_origen'-->
              <select id="id_ciudad_origen" name="ciudad_origen" class="form-control">
                <option value="" selected="selected">---------</option>
                <option value="Beni">Beni</option>
                <option value="Chuquisaca">Chuquisaca</option>
                <option value="Cochabamba">Cochabamba</option>
                <option value="La Paz">La Paz</option>
                <option value="Oruro">Oruro</option>
                <option value="Pando">Pando</option>
                <option value="Potosi">Potosi</option>
                <option value="Santa Cruz">Santa Cruz</option>
                <option value="Tarija">Tarija</option>
              </select>
            </div>
            <label for="" class="col-sm-5 control-label2">Codigo GL:</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="" name='codigo_gl'>
            </div>
            <label for="" class="col-sm-5 control-label2">Fecha de Ingreso:</label>
            <div class="col-sm-10">
              <input type="date" class="form-control" id="" name='fecha_ingreso'>
            </div>
            <label for="" class="col-sm-5 control-label2">Nombres:</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="" name='nombres'>
            </div>
            <label for="" class="col-sm-5 control-label2">Apellidos:</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="" name='apellidos'>
            </div>
            <label for="" class="col-sm-5 control-label2">CI:</label>
            <div class="col-sm-10">
              <input type="number" class="form-control" id="" name='ci'>
            </div>
            <label for="" class="col-sm-5 control-label2">Telefono:</label>
            <div class="col-sm-10">
              <input type="number" class="form-control" id="" name='telefono'>
            </div>
            <label for="" class="col-sm-5 control-label2">Cel:</label>
            <div class="col-sm-10">
              <input type="number" class="form-control" id="" name='cel'>
            </div>
          </div><!-- End form-group  -->
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="" class="col-sm-5 control-label2">Empresa:
              <button type="button" class='btn-success sbtn-xs'>Crear Empresa</button>
            </label>
            <div class="col-sm-10">
              <!--input type="email" class="form-control" id="" name='empresa'-->
              <select id="id_empresa" name="empresa" class="form-control">
                <option value="" selected="selected">---------</option>
                <option value="1">Blue Hawk</option>
                <option value="4">Boa Bolivia</option>
                <option value="5">Empetrol</option>
                <option value="6">MIEmpresa</option>
                <option value="7">Facebook</option>
              </select>
            </div>
            <label for="" class="col-sm-5 control-label2">Tramite:</label>
            <div class="col-sm-10">
              <!--input type="email" class="form-control" id="" name='tramite'-->
              <select id="id_tramite" name="tramite" class="form-control">
                <option value="" selected="selected">---------</option>
                <option value="1">Jubilacion</option>
                <option value="4">Invalidez</option>
                <option value="5">aaaaaa</option>
                <option value="6">qqq</option>
              </select>
            </div>
            <label for="" class="col-sm-5 control-label2">AFP:</label>
            <div class="col-sm-10">
              <!--input type="email" class="form-control" id="" name='afps'-->
              <select id="id_afps" name="afps" class="form-control">
                <option value="" selected="selected">---------</option>
                <option value="1">Futuro</option>
                <option value="3">Prevision</option>
              </select>
            </div>
            <label for="" class="col-sm-5 control-label2">Clinica:
              <button type="button" class='btn-success sbtn-xs'>Crear Clinica</button>
            </label>
            <div class="col-sm-10">
              <!--input type="email" class="form-control" id="" name='clinica'-->
              <select id="id_clinica" name="clinica" class="form-control">
                <option value="" selected="selected">---------</option>
                <option value="3">San Pedro</option>
              </select>
            </div>
            <label for="" class="col-sm-5 control-label2">Persona de referencia:</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="" name='persona_referencia'>
            </div>
            <label for="" class="col-sm-5 control-label2">Telefono de referencia:</label>
            <div class="col-sm-10">
              <input type="number" class="form-control" id="" name='telefono_per_referencia'>
            </div>
            <label for="" class="col-sm-5 control-label2">Cel de referencia:</label>
            <div class="col-sm-10">
              <input type="number" class="form-control" id="" name='cel_per_referencia'>
            </div>
          </div><!-- End form-group  -->
        </div>
      </div>
      <div class="row">
        <div class="col-md-5">
          <button type="submit" class="btn btn-success btn-lg btn-block">Crear Cliente</button>
        </div>
        <div class="col-md-5 col-md-offset-1">
          <a href="/listar_cliente/" class="btn btn-lg btn-block btn-warning">Cancel</a>
        </div>
      </div>

      </form>
  </div>
  
  

{% endblock content %}
  

templates/clientes/servicios_cliente.html
{% extends 'base_sistema.html' %}
{% load staticfiles %}

{% block content %}
{% load widget_tweaks %}
<section id="content">
  <section class="vbox">
    <header class="header bg-success bg-gradient">
          <ul class="nav nav-tabs">
              <li class="active"><a href="#static" data-toggle="tab">Crear Cliente</a></li>
          </ul>
      </header>
      <section class="scrollable wrapper">
        <div class="panel panel-default">
          <div class="container">
           <div class="row">
                <div class="col-md-8 col-sm-8 col-xs-12">

                  <div class="form-group">
                    <form class=""  method="POST" enctype='multipart/form-data' id="formcliente">
                      <div class="card-panel">
                        <h3 class="header2">Costos Cliente</h3>
                        {% csrf_token %} 


                        <div class="row">
                          <div class="col-md-6">
                              <div class="form-group {% if form.errors.nombres %} has-error {% endif %}">
                                  <label class="control-label">Informe Final</label>
                                  <input type="text" class="form-control" id="id_nombres" name="informe_final" value="{{costos.informe_final}}"/>
                                  <div class="help-block with-errors">
                                    {{form.errors.nombres|removetags:'ul li'}}
                                  </div>
                              </div>
                            </div>
                            <div class="col-md-6">
                              <div class="form-group {% if form.errors.apellidos %} has-error {% endif %}">
                                <label class="control-label">Fisioterapia</label>
                                <input type="text" class="form-control" id="id_apellidos" name="fisioterapia" value="{{costos.fisioterapia}}"/>
                                <div class="help-block with-errors">
                                  {{form.errors.apellidos|removetags:'ul li'}}
                                </div>
                              </div>
                            </div>
                        </div>

                        <div class="row">
                          <div class="col-md-6">
                              <div class="form-group {% if form.errors.edad %} has-error {% endif %}">
                                <label class="control-label">Medicina laboral</label>
                                <input type="text" class="form-control" id="id_edad" name="medicina_laboral" value="{{costos.medicina_laboral}}" />
                                <div class="help-block with-errors">
                                  {{form.errors.edad|removetags:'ul li'}}
                                </div>
                              </div>
                            </div>
                            <div class="col-md-6">
                              <div class="form-group {% if form.errors.ci %} has-error {% endif %}">
                                <label class="control-label">Puesto de trabajo</label>
                                <input type="text" class="form-control" id="id_ci" name="puesto_trabajo" value="{{costos.puesto_trabajo}}" />
                                <div class="help-block with-errors">
                                  {{form.errors.ci|removetags:'ul li'}}
                                </div>
                              </div>
                            </div>
                        </div>

                        <div class="row">
                          <div class="col-md-6">
                              <div class="form-group {% if form.errors.telefono %} has-error {% endif %}">
                                <label class="control-label">Trabajo social</label>
                                <input type="text" class="form-control" id="id_telefono" name="trabajo_social" value="{{costos.trabajo_social}}" />
                                <div class="help-block with-errors">
                                  {{form.errors.telefono|removetags:'ul li'}}
                                </div>
                              </div>
                            </div>
                            
                        </div>

                      

                     
                        

                      </div>

                      <div class="form-group">
                        <div>
                          <button class="btn btn-primary " id="save"  type="submit">
                            Guardar
                          </button>
                          <a href="/listar_cliente" class="btn  btn-success"><i class="left"></i> Volver  Atras</a>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>

          


            

           


          </div>
        </div>
      </section>
  </section>      
</section>
    {% endblock %}

    {% block js %}
    {% load staticfiles %}
     <!-- <script src="{% static "js/apps/clientes.js"%}"></script> -->
    
    <script>
    
    </script>
  {% endblock js %}